# Generated by Django 4.2.2 on 2023-06-13 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProviderUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("api_key", models.CharField(max_length=50)),
                ("secret_key", models.CharField(max_length=50)),
                (
                    "provider_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.provider"
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="License",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=50)),
                ("license_key", models.CharField(max_length=50)),
                ("expire_date", models.DateTimeField()),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Configuration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("leverage", models.IntegerField(default=10)),
                ("interval", models.CharField(default="15m", max_length=10)),
                ("margin_type", models.CharField(default="CROSSED", max_length=10)),
                ("volume_usdt", models.IntegerField(null=True)),
                (
                    "amount_usdt",
                    models.DecimalField(decimal_places=2, max_digits=20, null=True),
                ),
                (
                    "candle_change_ratio",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "profit_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                ("max_position_count", models.IntegerField(null=True)),
                ("is_bollinger_active", models.BooleanField(default=False)),
                ("check_position_mode", models.BooleanField(default=False)),
                ("blacklist", models.JSONField()),
                ("roes", models.JSONField()),
                (
                    "provider_user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.provideruser",
                    ),
                ),
            ],
        ),
    ]
