# Generated by Django 4.2.2 on 2023-06-13 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="provideruser",
            name="wallet_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
