# Generated by Django 4.2.2 on 2023-06-13 21:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_configuration_created_at_license_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuration",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 14, 0, 56, 31, 696223)
            ),
        ),
        migrations.AlterField(
            model_name="license",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 14, 0, 56, 31, 697374)
            ),
        ),
        migrations.AlterField(
            model_name="license",
            name="email",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="license",
            name="license_key",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="provider",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 14, 0, 56, 31, 696223)
            ),
        ),
        migrations.AlterField(
            model_name="provideruser",
            name="api_key",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="provideruser",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 14, 0, 56, 31, 696223)
            ),
        ),
        migrations.AlterField(
            model_name="provideruser",
            name="secret_key",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
