# Generated by Django 4.2.2 on 2023-06-13 21:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_configuration_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuration",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 13, 21, 59, 3, 14223)
            ),
        ),
        migrations.AlterField(
            model_name="license",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 13, 21, 59, 3, 14223)
            ),
        ),
        migrations.AlterField(
            model_name="provider",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 13, 21, 59, 3, 13222)
            ),
        ),
        migrations.AlterField(
            model_name="provideruser",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 13, 21, 59, 3, 13222)
            ),
        ),
    ]
