# Generated by Django 4.2.2 on 2023-06-13 22:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_configuration_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuration",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="license",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="provider",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="provideruser",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
