# Generated by Django 4.2.2 on 2023-06-21 12:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_configuration_provider_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="license",
            name="license_key",
            field=models.CharField(
                default=uuid.UUID("3d4a6847-af20-44cc-a81e-b1357e90c6fb"),
                max_length=50,
                unique=True,
            ),
        ),
    ]
