# Generated by Django 4.2.2 on 2023-06-21 12:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_alter_license_license_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="license",
            name="license_key",
            field=models.CharField(
                default=uuid.UUID("b72d7872-8fcc-473c-aabe-be1b4515a1d8"),
                max_length=50,
                unique=True,
            ),
        ),
    ]
