# Generated by Django 4.2.2 on 2023-06-21 14:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_alter_license_license_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="license",
            name="expire_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="license",
            name="license_key",
            field=models.CharField(
                default=uuid.UUID("c62782a0-e781-436e-8c7a-b0cd5f45951c"),
                max_length=50,
                unique=True,
            ),
        ),
    ]
